### ISSUE TITLE
отличие текущей реализации от https://github.com/shtrih-m/javapos_shtrih

### ISSUE THREAD

**Issue by whiskas** [shtrih-m/fr_drv_ng_examples#1]
добрый день! надо подключить фр штрих он-лайн, смотрим библиотеку, 
наткнулись на эту и на https://github.com/shtrih-m/javapos_shtrih

Вроде и тут и там есть jpos интерфейсы и возможность работать под android 

не подскажете в чем разница этих решений и какой лучше использовать в работе? (что удобнее в разработке, где есть поддержка по issue)

спасибо!

**Comment by swex** [comment]
see https://github.com/shtrih-m/fr_drv_ng/issues/2
