### ISSUE TITLE
Происходит exception при попытке печати на Smartpos mini

### ISSUE THREAD

**Issue by ola-skorp** [shtrih-m/fr_drv_ng_examples#12]
Происходит exception при попытке печати на Smartpos mini
Вот стек: https://gist.github.com/ola-skorp/d442864dbdbee40c7015841ad0f9436a
Вот строка, на которой происходит исключение:
SmartPosNative()
Файл libclassic_fr_drv_ng.so в проекте есть
![image](https://user-images.githubusercontent.com/14222295/60209308-0388ec00-9863-11e9-86d5-ab1df7de8470.png)
![image](https://user-images.githubusercontent.com/14222295/60209316-0c79bd80-9863-11e9-9db4-c0c9b677c7f4.png)
![image](https://user-images.githubusercontent.com/14222295/60209338-17345280-9863-11e9-8b3d-761466a6eee9.png)
![image](https://user-images.githubusercontent.com/14222295/60209348-1e5b6080-9863-11e9-9395-11a2a0ea5c53.png)
Ваше тестовое приложение открыло смену, но при печати чека попеременно выдаёт -8 Unknown error и 64: KKT: Неверное округление итога чека
То есть в тестовом приложении не возникает такого же exception'а как в нашем. В связи с этим у меня вопрос: что я могла сделать не так? Я уже скопировала все файлы библиотеки в тестовом проекте, но ничего не изменилось

**Comment by ola-skorp** [comment]
typealias SmartPosNative = classic_interface

**Comment by swex** [comment]
1. смущает только что у вас в нативных библиотеках есть gnustl_shared.so. Этот рантайм устарел, его даже уже в [документации](https://developer.android.com/ndk/guides/cpp-support) нет.
2. проверьте что у вас все aar, jar и so из [актуальных сборок](https://github.com/shtrih-m/fr_drv_ng/releases).
3. если не поможет - давайте минимальный проект где воспроизводится

**Comment by ola-skorp** [comment]
Я взяла все файлы из примера https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_fr_drv_ng_android_example

**Comment by swex** [comment]
> Я взяла все файлы из примера https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_fr_drv_ng_android_example

В примере файлы не актуальные, а какой-то срез. Возьмите **все** файлы из **последней** сборки.

**Comment by ola-skorp** [comment]
Сделала приложение для теста - ошибка не воспроизводится. Может ли что-то конфликтовать с библиотекой? Я удалила всё из jniLibs и скопировала из тестового проекта, но ошибка продолжает воспроизводиться, тогда как с теми же файлами на тестовом приложении она не воспроизводится

**Comment by swex** [comment]
1. какая железка, какая архитектура?
2. покажите актуальное дерево jniLibs
3. ну и md5 наших so, aar и jar :smiley: 
4. может в adb что-то пишется выше стектрейса приложения? Возможно туда ругается линкер и есть какие-то подробности ошибки

**Comment by ola-skorp** [comment]
![image](https://user-images.githubusercontent.com/14222295/60261885-95d1d400-98e5-11e9-80d4-c26eb04fcd67.png)

**Comment by ola-skorp** [comment]
SHTRIH-SMARTPOS-F_MINI

**Comment by ola-skorp** [comment]
Как добыть md5?

**Comment by swex** [comment]
md5 снять можно множеством утилит. md5sum, например.
Не знаю чем могу еще помочь. Попробуйте перетащить свой код в рабочий проект, может так выяснится в чем дело.
Идеально было бы если бы у вас был проект в котором воспроизводится проблема.

**Comment by ola-skorp** [comment]
Причина в двух библиотеках 
![image](https://user-images.githubusercontent.com/14222295/60272276-84e08d00-98fc-11e9-93fd-2f05f64fd872.png)
Вот ссылка на проект https://drive.google.com/open?id=1fAJjzDzdPhalXF7ckUkVJDwbDICl75Ij

**Comment by ola-skorp** [comment]
Библиотеки payme и ingenico

**Comment by swex** [comment]
Подтвердились опасения из первого поста. Эти ребята собирают свои библиотеки с устаревшим NDK. 
как проверить:
1. Разархивируем их aar
2. Переходим в директорию с .so
```bash

objdump -x *|grep -i NEED
  NEEDED               libft_ePayPOSNDK.so
  NEEDED               liblog.so
  NEEDED               libc.so
  NEEDED               libm.so
  NEEDED               libstdc++.so
  NEEDED               libdl.so
  VERNEED              0x000013fc
  VERNEEDNUM           0x00000001
  NEEDED               liblog.so
  NEEDED               libstdc++.so
  NEEDED               libm.so
  NEEDED               libc.so
  NEEDED               libdl.so
```
3. вместо `libstdc++.so` должен быть `libc++_shared.so`

Вот [здесь](https://developer.android.com/ndk/guides/cpp-support) видно что тулчейн GNU уже не поддерживается и объявлен устаревшим уже как больше года.
В одном процессе не могут работать 2 разных c++ рантайма.
Необходимо обратиться к ним за разъяснениями думаю они могут пересобрать библиотеки с актуальным SDK.

**Comment by ola-skorp** [comment]
Я временно убрала из проекта payme и ingenico. Теперь вот такая ошибка https://gist.github.com/ola-skorp/3afacbeb583317df2c425bb1ef639d07

**Comment by ola-skorp** [comment]
Перезагрузка не помогла

**Comment by swex** [comment]
метод использует пароль. Посмотрите [пример](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_interface/main.cpp#L687) там сразу после создания объекта назначаются пароли.
Ну и читайте [доку на методы](https://github.com/shtrih-m/fr_drv_ng/wiki/Methods#group___base_methods_1gaae87ee5687c54e26fde7a2ba1dc8525f)

**Comment by ola-skorp** [comment]
Как узнать пароль? Я добавила как в примере, но ошибка осталась

**Comment by swex** [comment]
Пароль узнать можно из таблицы 2, но для чтения таблиц нужен пароль администратора :). На то он и пароль...
В настоящее время пароли не очень актуальны, т.к. между ККТ и оператором всегда высокоуровневый софт. Обычно используются пароли по умолчанию 1 для пользователя и 30 для администратора.
Хорошо бы почитать [общее руководство по работе с ККТ](https://www.shtrih-m.ru/docs/download.php?file=28008&iblock=21)
Попробуйте отменить от администратора, методом `SysAdminCancelCheck`

давайте заводить отдельные заявки для других проблем. Эту предлагаю закрыть
