### ISSUE TITLE
Как узнать количество символов модели.

### ISSUE THREAD

**Issue by sergo44** [shtrih-m/fr_drv_ng_examples#13]
Коллеги. Подскажите пожалуйста, как узнать, количество символов шириной 1 и 2 (2 как понимаю, это половина от ширины 1), которые вмещаются на чековую ленту. Разрабатываем ПО для Андройд (после разработки для COM объекта), для драйвера (COM 4.14) такого метода не нашли. Перенос строк не работает (тестировали через тест драйвера ФР).  Если в новой версии COM драйвера есть такая возможность, подскажите. Печатаем много произвольного текста (билеты). Спасибо.

**Comment by swex** [comment]
Некоторые модели умеют автоматически переносить строки.
Ищите в `classic_interface.h` слово `перенос`
Для того чтобы узнать кол-во символов произвольным шрифтом нужно что-то вроде этого:
```c++
ci.Set_FontType(1);//номер шрифта для которого хотим узнать ширину
int oldPassword =  ci->Get_Password();
ci->Set_Password(ci->Get_SysAdminPassword());
ci->GetFontMetrics();
int symbolsPerLine = ci->Get_PrintWidth() / ci->Get_CharWidth();
ci->Set_Password(oldPassword);
```
имеет смысл закешировать эти ширины...

**Comment by sergo44** [comment]
Спасибо.
