### ISSUE TITLE
Incorrect data about time period between fiscal documents

### ISSUE THREAD

**Issue by IamWinWon** [shtrih-m/fr_drv_ng_examples#16]
Добрый день!

Взял последние сборки тут https://github.com/shtrih-m/fr_drv_ng/releases.
В тестировании примера https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_fr_drv_ng_android_example

Принтер ШтрихМ Нано-Ф (пробовал и с МГМ, и без)
Ошибки: 
[E] Incorrect data about time period between fiscal documents
[E] Command is not supported.

UPD:Скачал Ваш код из одного из тредов - ошибка пропала. Но появилась другая.
Теперь другая ошибка:
Inout error на ci.WaitForPrinting()

**Comment by swex** [comment]
На какую команду ошибка? нужен лог.
Вот как настраивается логгирование:
```c++
    //!
    //! @brief Логгирование в драйвере глобальное и включено всегда.
    //!
    //! Управление происходит через следующие переменные окружения <br>
    //! * FR_DRV_DEBUG_CONSOLE - если определено весь вывод лога будет на stderr <br>
    //! * FR_DRV_LOG_PATH - путь файла лога(по умолчанию fr_drv.log в рабочей директории)<br>
    //! * FR_DRV_LOG_FILE_COUNT - кол-во ротаций(по умолчанию 2)<br>
    //! * FR_DRV_LOG_PART_SIZE - размер части в байтах (по умолчанию 1024 * 1024 * 10)<br>
    //! * FR_DRV_LOG_FLAGS - флаги логгирования, битовая маска со следующими ключами(по умолчанию
    //! всё включено)
```
Почитать по общим вопросам: [вот]( https://github.com/shtrih-m/fr_drv_ng/wiki/%D0%9A%D0%B0%D0%BA-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D1%81-classic_fr_drv_ng)

**Comment by IamWinWon** [comment]
Inout error **на** команду ci.WaitForPrinting().
Вообще весь пример подчистил и надеялся запустить просто тест.
Поможете как это сделать в правильном порядке?
`executeAndHandleError(new Callable<Integer>() {
            @Override
            public Integer call() {
                return ci.Connect();
            }
        });`

`executeAndHandleError(new Callable<Integer>() {
            @Override
            public Integer call() {
                return ci.Test();
            }
        });`

**Comment by swex** [comment]
1. Нужен лог, только с логом можно понять в чем проблема
2. Для  НАНО предпочтительней протокол использовать v2
3. Удостоверьтесь что у вас актуальная прошивка на НАНО
4. Попробуйте сменить транспорт с bluetooth на wifi

**Comment by IamWinWon** [comment]
В общем получилось распечатать тестовый чек. Сменил на v2.
Прочитал внимательно инструкцию.
Спасибо
