### ISSUE TITLE
Режим разрешения технологического обнуления

### ISSUE THREAD

**Issue by IamWinWon** [shtrih-m/fr_drv_ng_examples#17]
Наш фискальник вошёл в этот режим. Помогите найти порядок действий вернуть его к нормальной работе.

**Comment by swex** [comment]
В этом случае необходимо выполнить технологическое обнуление и установить текущую дату/время.
Последовательность  такая:
`ResetSettings`, `SetDate`, `SetTime`, `ConfirmDate`

**Comment by IamWinWon** [comment]
Спасибо. Вечером не нашёл. Буду внимательней.
