### ISSUE TITLE
Имя кассира и и администратора/инн/место продажи

### ISSUE THREAD

**Issue by IamWinWon** [shtrih-m/fr_drv_ng_examples#18]
Добрый день!

Помогите с примером classic_interface как задать имена кассира и системного администратора, Так же место продажи так чтобы они печатались автоматически во время действий с фискальником.

`ci.Set_Password(userPassword);
                        ci.Set_TableNumber(2);
                        ci.Set_RowNumber(1);
                        ci.Set_FieldNumber(7);
                        ci.Set_ValueOfFieldInteger(1);
                        ci.Set_ValueOfFieldString(receiptShtrih.getReceipt().getOperator().getName());
                        ci.WriteTable();`
Делаю подобно примерам, что нашёл, но имя так и остается 1. Как выставить адреса продажи вообще не нашёл.

**Comment by swex** [comment]
Вы взяли код из примера: `fsRegistrationReport пример печати отчета о регистрации `
И пытаетесь поменять таблицу №2: `Пароли кассиров и администраторов`
делается это как-то так:
```c++
        ci.Set_TableNumber(2); //таблица
        ci.Set_RowNumber(1); //первый пользователь
        ci.Set_FieldNumber(2); //второе поле - имя(первое поле - пароль)
        ci.Set_ValueOfFieldString("new_username");
        checkResult(ci.WriteTable());
```

**Comment by IamWinWon** [comment]
> Вы взяли код из примера: `fsRegistrationReport пример печати отчета о регистрации `
> И пытаетесь поменять таблицу №2: `Пароли кассиров и администраторов`
> делается это как-то так:
> 
> ```c++
>         ci.Set_TableNumber(2); //таблица
>         ci.Set_RowNumber(1); //первый пользователь
>         ci.Set_FieldNumber(2); //второе поле - имя(первое поле - пароль)
>         ci.Set_ValueOfFieldString("new_username");
>         checkResult(ci.WriteTable());
> ```
Спасибо, опробую.
Скажите, пожалуйста, Set_FieldNumber - где можно найти детальное описание полей, в вики не нашёл, чтобы подобных вопросов не было.

**Comment by swex** [comment]
> Скажите, пожалуйста, Set_FieldNumber - где можно найти детальное описание полей, в вики не нашёл, чтобы подобных вопросов не было.

Это стоит почитать "[общее руководство](https://exam.shtrih-m-partners.ru/assets/materials/Obshchee_rukovodstvo_po_nastroyke_KKT_22_06_18.pdf)"
