### ISSUE TITLE
Информация о смене.

### ISSUE THREAD

**Issue by IamWinWon** [shtrih-m/fr_drv_ng_examples#19]
Перелопатил всю вики и не нашёл возможности взять такие данные как:
(для отчёта при закрытии смены)
1. Сумму и количество внесений/изъятий.
2. Сумму инкасации.
3. Сумму продаж и возвратов наличными/электронными.

Это вообще возможно, если да то какими методами?

**Comment by swex** [comment]
Почитайте [общее руководство](https://www.shtrih-m.ru/docs/download.php?file=32005&iblock=21) о денежных и операционных регистрах и сморите методы `GetOperationReg` и `GetCashReg`
