### ISSUE TITLE
Проведение продажи без печати чека (отправка клиенту на его e-mail)

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng_examples#2]
Возможно ли проводить продажу (возврат и др. возможные операции) на смартпосе без печати бумажного чека (но с сохранением операции в фискальный  регистратор)? Спасибо.

**Comment by try2bajed1** [comment]
а еще я тут никого назначать не могу, дайте какие-нибудь права

**Comment by try2bajed1** [comment]
> 1. Чтобы не печатать документ на принтере специальное свойство  `SkipPrint`
> 2. Чтобы передать email клиента необходимо воспользоваться методом `FNSendCustomerEmail`
автокомплит в джаве выдает лишь методы
SkipDateTimeField
SkipUndoDateTimeField

может быть у меня старая версия драйвера?

**Comment by swex** [comment]
Нет таких свойств/методов у нас, кажется мы о разном говорим.

**Comment by try2bajed1** [comment]
возможно, я забыл уточнить что речь идет о смартпосе

**Comment by swex** [comment]
я не понимаю. Покажите код/лог, через какой объект работаете с ККТ?

**Comment by try2bajed1** [comment]
работаю с андройд драйвером на штрихм смартпос. 

package ru.shtrih_m.fr_drv_ng.classic_interface;
public class ClassicImpl implements Classic {  }

**Comment by try2bajed1** [comment]
![_025](https://user-images.githubusercontent.com/878652/47645117-138be700-db81-11e8-9a51-6c71226522a4.png)
у меня нет такого метода. Может быть причина в том что версия драйвера не последняя?

**Comment by swex** [comment]
Свойство `SkipPrint` появлось 29.08.18. Да, похоже у вас очень старая версия. Берите актуальную [сборку](https://github.com/shtrih-m/fr_drv_ng/releases)

**Comment by try2bajed1** [comment]
а для новой версии нужен джарник classic_java_fr_drv_ng-1.1.jar ? Или сейчас уже достаточно  в моем текущем проекте он присутствует. И в случае со смартпосом какую библиотеку использовать для андройда ? обычную или 64 битную?

**Comment by swex** [comment]
classic_java_fr_drv_ng-1.1.jar стар, работать будет, т.к. JNI остается такой же но там не все актуальные свойства/методы есть.
в релизах есть архив: fr_drv_ng_java_wrappers_$VERSION.zip внутри него всегда актуальный jar

**Comment by try2bajed1** [comment]
а по поводу версии под 64 бита? какую из сборок качать для смартпоса?

**Comment by try2bajed1** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/ru.insales.ekam-1/lib/arm/libclassic_fr_drv_ng.so" is 64-bit instead of 32-bit
Не повезло ), но зато ответ нашелся

**Comment by try2bajed1** [comment]
для КЯ в поле 48 "КАССОВЫЕ ЧЕКИ (БСО) В ЭЛЕКТРОННОЙ ФОРМЕ" в табл.1 записать 1. 
А не покажете пример, каким образом записывать в таблицы?

**Comment by swex** [comment]
https://github.com/shtrih-m/fr_drv_ng/wiki/%D0%A7%D0%B0%D1%81%D1%82%D0%BE-%D0%B7%D0%B0%D0%B4%D0%B0%D0%B2%D0%B0%D0%B5%D0%BC%D1%8B%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B-%D0%BF%D1%80%D0%BE-classic_fr_drv_ng#EditTable

**Comment by try2bajed1** [comment]
В принципе у меня получилось провести продажу без печати, спасибо.
