### ISSUE TITLE
Библиотеки на arm 64

### ISSUE THREAD

**Issue by lunaticShoe** [shtrih-m/fr_drv_ng_examples#24]
Есть ли возможность где то получить или собрать библиотки libc++_shared.so, libclassic_fr_drv_ng.so, libcppbase_fr_drv_ng.so под arm 64? это требуется для публикации в Google Play.

**Comment by swex** [comment]
Конечно есть! В [релизах](https://github.com/shtrih-m/fr_drv_ng/releases) есть сборка `fr_drv_ng_android_arm64-v8a`

**Comment by lunaticShoe** [comment]
> 
> 
> Конечно есть! В [релизах](https://github.com/shtrih-m/fr_drv_ng/releases) есть сборка `fr_drv_ng_android_arm64-v8a`

Спасибо
