### ISSUE TITLE
Ошибка 99: Переполнение диапазона отделов

### ISSUE THREAD

**Issue by lunaticShoe** [shtrih-m/fr_drv_ng_examples#25]
Здравствуйте возникает такая ошибка при печати чека, хотя устанавливаем Set_Department(1)
Ошибка происходит у клиента и пока что нет возможности провести отладку.
`               if (cartItems.isNullOrEmpty())
                    return@coroutineScope

                connect()
                executeAndHandleError(Callable { ci.WaitForPrinting() })
                if (ci.Get_ECRMode() == classic_interface.PrinterMode.PM_SessionClosed.swigValue()
                        || ci.Get_ECRMode() == classic_interface.PrinterMode.PM_SessionOpenOver24h.swigValue()) {
                    throw Exception("Сессия в неправильном состоянии, закройте и откройте смену повторно")
                }

                if (ci.Get_ECRMode() == classic_interface.PrinterMode.PM_OpenedDocument.swigValue()) {

                    ci.Set_Password(sysAdminPassword)
                    executeAndHandleError(Callable { ci.SysAdminCancelCheck() })
                    ci.Set_Password(password)
                }

                var sum: Long = 0
                ci.Set_CheckType(0) //продажа

                executeAndHandleError(Callable { ci.OpenCheck() })

                for (i in 0 until cartItems.size) {
                    val item = cartItems[i]
                    val price= BigDecimal(item.priceClient.toDouble() * 100).setScale(2, RoundingMode.HALF_EVEN).toLong()
                    val quantity = BigDecimal(item.factWeight.toDouble()).setScale(2, RoundingMode.HALF_EVEN).toDouble()

                    var title = item.name //${i+1}           

                    ci.Set_CheckType(1) //приход
                    ci.Set_Quantity(quantity)
                    ci.Set_Price(price)
                    val total = (price * quantity).toLong()
                    sum += total
                    ci.Set_Summ1Enabled(true) //рассчитывает касса
                    ci.Set_Summ1(total)
                    ci.Set_TaxValueEnabled(false)
                    ci.Set_Tax1(1) //НДС 18%
                    ci.Set_Department(1)
                    ci.Set_PaymentTypeSign(4) //полный рассчет
                    ci.Set_PaymentItemSign(1) //товар

                    ci.Set_StringForPrinting(title)
                    executeAndHandleError(Callable { ci.FNOperation() })
                }

                if (deliveryCost > 0) {
                    val deliveryCostL = deliveryCost.toLong()
                    ci.Set_CheckType(1) //приход
                    ci.Set_Quantity(1.0)
                    ci.Set_Price(deliveryCostL)
                    sum += deliveryCostL
                    //ci.Set_Summ1Enabled(true) //рассчитывает касса
                     ci.Set_Summ1(deliveryCostL)
                    ci.Set_TaxValueEnabled(false)
                    ci.Set_Tax1(1) //НДС 18%
                    ci.Set_Department(1)
                    ci.Set_PaymentTypeSign(4) //полный рассчет
                    ci.Set_PaymentItemSign(4) //товар
                    ci.Set_StringForPrinting("Стоимость доставки")
                    executeAndHandleError(Callable { ci.FNOperation() })
                }

                val cashSum = BigDecimal(gainedCash.toDouble())
                    .multiply(BigDecimal(100))
                    .setScale(2, RoundingMode.HALF_EVEN).toLong()
                val eMoneySum = BigDecimal(gainedCard.toDouble())
                    .multiply(BigDecimal(100))
                    .setScale(2, RoundingMode.HALF_EVEN).toLong()
                    //val cashSum = gained.toLong() * 100
//                    if (cashSum != sum)
//                        ++cashSum
                ci.Set_Summ1(cashSum) // Наличные
                ci.Set_Summ2(eMoneySum) //Электронными (totalCost * 100).toLong()

                ci.Set_Summ3(0)
                ci.Set_Summ4(0)
                ci.Set_Summ5(0)
                ci.Set_Summ6(0)
                ci.Set_Summ7(0)
                ci.Set_Summ8(0)
                ci.Set_Summ9(0)
                ci.Set_Summ10(0)
                ci.Set_Summ11(0)
                ci.Set_Summ12(0)
                ci.Set_Summ13(0)
                ci.Set_Summ14(0)
                ci.Set_Summ15(0)
                ci.Set_Summ16(0)
               // ci.Set_RoundingSumm(99); // Сумма округления
                ci.Set_TaxValue1(0) // Налоги мы не считаем

                ci.Set_TaxValue2(0)
                ci.Set_TaxValue3(0)
                ci.Set_TaxValue4(0)
                ci.Set_TaxValue5(0)
                ci.Set_TaxValue6(0)
                ci.Set_TaxType(1) // Основная система налогообложения

                val text = String.format(
                        context.getString(R.string.check_out_check_promo_points_discarded),
                        totalPointDiscarded)

                ci.Set_StringForPrinting(text)
                executeAndHandleError(Callable { ci.FNCloseCheckEx() })
                executeAndHandleError(Callable { ci.WaitForPrinting() })`

**Comment by swex** [comment]
какая? давайте лог.

**Comment by lunaticShoe** [comment]
> 
> 
> какая? давайте лог.

Ошибка ККТ 99: Переполнение диапазона отделов
Ошибка возникает у клиента и отладить или более подробно посмотреть пока нет возможности.

**Comment by swex** [comment]
ждём лог

**Comment by lunaticShoe** [comment]
> 
> 
> ждём лог

пока что не удалось изначальную проблему воспроизвести, при оплате наличными идет ошибка: 51: ККТ: некорректные параметры в команде, судя по всему речь о методе FNCloseCheckEx()

лог: https://drive.google.com/file/d/1zsdlaBgvVxan10FiUpWjyBt2jre_Ppq6/view?usp=sharing

**Comment by swex** [comment]
вот же подробное описание в логе:
```
07-22 21:18:31.020  2343  2376 D cashcore: cashcore: 22.07.21 21:18:31.020335 [!]     #0197 КОМАНДА FF45H: КОД ОШИБКИ 33h (051) "ККТ: Некорректные параметры в команде <0x00330019: в параметре СНО передана неверная система налогообложения>".

```

**Comment by lunaticShoe** [comment]
> 
> 
> вот же подробное описание в логе:
> 
> ```
> 07-22 21:18:31.020  2343  2376 D cashcore: cashcore: 22.07.21 21:18:31.020335 [!]     #0197 КОМАНДА FF45H: КОД ОШИБКИ 33h (051) "ККТ: Некорректные параметры в команде <0x00330019: в параметре СНО передана неверная система налогообложения>".
> ```

Это я так понимаю речь о ci.Set_TaxType(1) 
Какая правильная в данном случае должна быть?

**Comment by swex** [comment]
Видимо ОСН системы налогообложения не было в документе пере/регистрации. Смотрите что там в этом ФН фискализацией.

**Comment by lunaticShoe** [comment]
> 
> 
> Видимо ОСН системы налогообложения не было в документе пере/регистрации. Смотрите что там в этом ФН фискализацией.

Добрый день! Получилось забрать у клиента кассу и проверить настройки налогообложения ФН. Действительно, в настройках стояла отличная от подаваемой через API. Есть тогда вопрос: Есть ли возможность прочитать эту настройку?

**Comment by lunaticShoe** [comment]
Уже сам разобрался. Спасибо.
