### ISSUE TITLE
обновление драйвера до последней версии 1.4.3-4-g7acc61c.  java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/ru.insales.ekam-2/lib/arm/libclassic_fr_drv_ng.so" has unexpected e_machine: 3

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng_examples#3]
собственно в момент инициализации инстанса падаю с такой ошибкой
 java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/ru.insales.ekam-2/lib/arm/libclassic_fr_drv_ng.so" has unexpected e_machine: 3

**Comment by swex** [comment]
libcppbase_fr_drv_ng.so тоже рядом?

**Comment by swex** [comment]
а libc++_shared.so из архива? там в logcat должно написать что именно не линкуется

**Comment by try2bajed1** [comment]
файлы все из архива. Я сейчас попробую собрать ваш проект с гитхаба. Может быть сам что-то где-то не добавил. Хотя джарник на месте,aar, so тоже...

**Comment by try2bajed1** [comment]
ваш тестовый проект валится с ошибкой
couldn't find "libclassic_fr_drv_ng.so"couldn't find "libclassic_fr_drv_ng.so"

**Comment by swex** [comment]
только что собрал у себя с использованием архивов: **fr_drv_ng_java_wrappers_1.4.3-4-g7acc61c.zip** и **fr_drv_ng_android_armeabi-v7a_1.4.3-4-g7acc61c.zip** и всё ок.

**Comment by try2bajed1** [comment]
правильно ли я понимаю, что нативные драйверы должны лежать в папке armeabi-v7a ?
внутри fr_drv_ng_java_wrappers_1.4.3-4-g7acc61c.zip  лежит файл classic_java_fr_drv_ng-1.4.1.jar. Не критично, что версии немного расходятся?

**Comment by swex** [comment]
1.4.3-4-g7acc61c - это версия центрального репозитория. 1.4.1.jar значит с 1.4.1 не менялся java интерфейс. В целом можно смело брать jar из актуальной сборки и всё будет работать.

Пути зависят от архитектур, но для смартпоса хватит и armeabi-v7a.

Вот проект целиком:
[classic_fr_drv_ng_android_example.zip](https://github.com/shtrih-m/fr_drv_ng_examples/files/2529965/classic_fr_drv_ng_android_example.zip)
Вот, получившийся у меня пакет
[app-debug.zip](https://github.com/shtrih-m/fr_drv_ng_examples/files/2529969/app-debug.zip)

**Comment by try2bajed1** [comment]
да, с вашими исходниками я не нарываюсь в ошибки линкования либы. Видимо сам что-то не так подключил. Буду разбираться. Мне кажется я как то некорректно подключаю aar

**Comment by swex** [comment]
ок
