### ISSUE TITLE
Консольный тест драйвер, признак маркировки при регистрации

### ISSUE THREAD

**Issue by elchako** [shtrih-m/fr_drv_ng_examples#30]
Добрый день!
Использую консольный тест драйвер для перерегистрации ФР.
На счет перерегистрации на ФФД 1.2 помогли, спасибо. https://github.com/shtrih-m/fr_drv_ng_examples/issues/28

Осталось понять как выставить признак маркировки при перерегистрации через консоль.
В гугле ответа не нашел.

**Comment by swex** [comment]
Смотрите "[общее руководство](https://exam.shtrih-m-partners.ru/assets/materials/Obshchee_rukovodstvo_po_nastroyke_KKTver12_041220.zip)"  там есть таблица с битовыми полями "Режим работы ККТ":
Биты с 0 по 5 - это Режим работы(workmode) который передается в команду регистрации
Биты с 6 по 13 - это Т18П21(таблица 18 - FiscalStorage, поле 21 - Расширенные признаки работы ККТ)

**Comment by elchako** [comment]
с вопросом выше понял
но возник другой, при подаче команды получаю ошибку
$EXE kkt-rereg-report 1.1.22
#1-Налогообложение ОСН, 1-реж.работы Шифрование, 22-причина изменение ФФД
Не важно какую причину ставлю 1.1.22, пробовал 1.1.4, 1.1.3
![image](https://user-images.githubusercontent.com/82187221/149628538-81a2c24d-5059-447e-90ca-8ca68eb131fe.png)

![image](https://user-images.githubusercontent.com/82187221/149628505-0f48ab5a-d060-4f9b-a302-a13f6b0625e7.png)
![image](https://user-images.githubusercontent.com/82187221/149628679-3f1b3eba-f650-471d-a6f8-711f0760c463.png)

**Comment by elchako** [comment]
Может проблема в этом? 
При подаче команды **kkt-reg-begin 4** получаю ошибку. Попробовал указать 2 для теста, с 2 ошибки нет.

$EXE kkt-reg-begin 4
Неизвестная команда, неверный формат посылки или неизвестные параметры

**Comment by elchako** [comment]
Решено тут https://github.com/shtrih-m/fr_drv_ng/issues/175
