### ISSUE TITLE
Сборка драйвера

### ISSUE THREAD

**Issue by Styort** [shtrih-m/fr_drv_ng_examples#32]
Здравствуйте.
Разрабатываю на .NET 6.0 кроссплатформленное решение для работы с вашими кассами. 
У меня несколько вопросов:
1) Правильно ли я понимаю, что единой обёртки для драйвера, которая будет работать и на винде и на линуксе - нет? Надо собирать под каждую платформу обёртку и в зависимости от ОС использовать либо одну, либо другую?
2) Начал собирать обёртку по данному примеру из [README](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_csharp/README.md). Через N часов попыток, прошерстив ваши issues, удалось это сделать. Но запуская ваш [пример](https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_csharp) (предварительно закинув туда все сгенерированные swig-ом .cs файлы и подкинув classic_fr_drv_ng и полученную обёртку classic_fr_drv_ng_csharp),  получаю результат: ![скриншоте](https://user-images.githubusercontent.com/10030099/181477239-f78eca7b-d44f-460b-9adb-51f2794aa4dd.png)
Причем, интересно то, что если я ставлю брейкпоинт после создания экземпляра classic_interface и начинаю идти дальше по шагам, то в консоли появляется эта ошибка после первого же обращения к драйверу (ci.RandomSequence), а если брейкпоинт не ставлю, то приложение завершается без ошибок (с кодом 0), но по [логу fr_drv_ng](https://github.com/shtrih-m/fr_drv_ng_examples/files/9207991/fr_drv_ng.log), видно, что методы выполняются с ошибками.
Можете подсказать, в чем именно может быть проблема и как решить?

**Comment by swex** [comment]
1. Да драйвер - нативная библиотека, она под каждую платформу собирается отдельно, как и обертки C# обертка под Windows и Linux это тоже нативные библиотеки. Тоже каждая под свою платформу.
2. Не знаю специфики C#, но скорее всего это опять: https://github.com/shtrih-m/fr_drv_ng/issues/64

PS: Не знаю, подходит ли это вам, но можете использовать [json-rpc](https://github.com/shtrih-m/fr_drv_ng_examples/blob/master/classic_jsonrpc/README.md) в этом случае можно забыть об обертках, в C# в стандартной библиотеке вроде бы есть websocket и json-rpc

**Comment by Styort** [comment]
1. Ок, понял, спасибо.
2. Да, действительно, проблема была в этом. Помогло, спасибо!

Рассмотрю данный вариант.
Просто решил пойти через обёртки, т.к. уже есть готовое решение для винды с вашим драйвером (Interop.DrvFRLib), а тут, насколько я понимаю, интерфейс 1 в 1 с ним. По сути - мне нужно только уметь разворачивать эти обёртки и использовать нужную в разных ОС.

**Comment by Styort** [comment]
Ок, понял, спасибо.
Да, действительно, проблема была в этом. Помогло, спасибо!
Рассмотрю данный вариант.
Просто решил пойти через обёртки, т.к. уже есть готовое решение для винды с вашим драйвером (Interop.DrvFRLib), а тут, насколько я понимаю, интерфейс 1 в 1 с ним. По сути - мне нужно только уметь разворачивать эти обёртки и использовать нужную в разных ОС.

**Comment by swex** [comment]
Имейте в виду: интерфейс старается соответствовать DrvFR, но тестировать свой код нужно именно с оберткой т.к. в деталях поведение может отличаться.

**Comment by Styort** [comment]
> Имейте в виду: интерфейс старается соответствовать DrvFR, но тестировать свой код нужно именно с оберткой т.к. в деталях поведение может отличаться.

Да, я это понимаю. Спасибо.
