### ISSUE TITLE
Список кодов ошибок

### ISSUE THREAD

**Issue by DmitryBoychuk** [shtrih-m/fr_drv_ng_examples#36]
Где можно посмотреть список всех возможных кодов ошибок и расшифровок, которые возникают при работе с classic_interface?

**Comment by swex** [comment]
ошибки >= 0 возвращаются от ККТ, < 0 от драйвера. ошибки ККТ можно посмотреть в протоколе: https://exam.shtrih-m-partners.ru/assets/materials/ProtokolKKT_1_17.zip
ошибки драйвера лучше просто смотреть описание через `ResultCodeDescription`

**Comment by swex** [comment]
В ККТ на основе КЯ есть возможность получить человекочитаемое подробное описание ошибки: см `DFE_AutoReadDetailedErrorDescription`
