### ISSUE TITLE
Отчет о регистрации ККТ - неверный тип отчета

### ISSUE THREAD

**Issue by surfernsk** [shtrih-m/fr_drv_ng_examples#37]
в примере отчет о регистрации не верно указан тип отчета - 1
```
ci->Set_ReportTypeInt(1); //Отчет о регистрации КТТ
```
а должен быть 0:
```
ci->Set_ReportTypeInt(0); //Отчет о регистрации ККТ
```
PR #35

**Comment by swex** [comment]
Вообще пример сделан для отчета о перерегистрации в связи с заменой ФН, т.к. такой отчет нужно будет формировать при каждой замене ФН, а начальный отчет о регистрации ККТ только раз. Поэтому тут думаю стоит просто поправить комментарий, а не менять значение типа отчета.
