### ISSUE TITLE
Вопросы по получению тегов 2109 и 2105

### ISSUE THREAD

**Issue by ConsperSerj** [shtrih-m/fr_drv_ng_examples#41]
Добрый день. Провожу проверку маркировки. Получил ответ положительный. Но вот не могу понять откуда брать данные для заполнения тегов 
1) Ответ ОИСМ о статусе товара. (2109)
2) Код обработки запроса. (2105)

Подскажите пожалуйста какие методы у вас отдают данные для этих тегов?

**Comment by ConsperSerj** [comment]
Если я правильно понимаю то 2109 можно заполнять на основе KMServerCheckingStatus смотря на 3 бит. Но, 2109 может быть одно из 3 значений

1)Планируемый статус товара корректен
2)Планируемый статус товара некорректен
3)Оборот товара приостановлен

И получается что если смотреть на 3 бит, то можно понять 1 или 2 значение. Но вот как понять что "Оборот товара приостановлен"?

**Comment by swex** [comment]
https://github.com/shtrih-m/fr_drv_ng/issues/225
