### ISSUE TITLE
Не могу слинковать библиотеку под golang 

### ISSUE THREAD

**Issue by offbrok** [shtrih-m/fr_drv_ng_examples#43]
Сделал все как описано в гайде

[https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_go](https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_go)

По итогу при go build .

```c:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\offbr\AppData\Local\Temp\go-link-1437089264\000011.o:C:\projects\golang\shtrihm\app\classic_fr_drv_ng_go/classic_interface_wrap.cxx:24423: undefined reference to `classic_interface::Set_FirstDocumentNumber(int)'
c:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\offbr\AppData\Local\Temp\go-link-1437089264\000011.o:C:\projects\golang\shtrihm\app\classic_fr_drv_ng_go/classic_interface_wrap.cxx:24448: undefined reference to `classic_interface::Set_ItemStatus(int)'
c:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\offbr\AppData\Local\Temp\go-link-1437089264\000011.o:C:\projects\golang\shtrihm\app\classic_fr_drv_ng_go/classic_interface_wrap.cxx:24473: undefined reference to `classic_interface::Set_CheckItemMode(int)'
c:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\offbr\AppData\Local\Temp\go-link-1437089264\000011.o:C:\projects\golang\shtrihm\app\classic_fr_drv_ng_go/classic_interface_wrap.cxx:24498: undefined reference to `classic_interface::Set_CheckItemLocalResult(int)'
c:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\offbr\AppData\Local\Temp\go-link-1437089264\000011.o:C:\projects\golang\shtrihm\app\classic_fr_drv_ng_go/classic_interface_wrap.cxx:24523: undefined reference to `classic_interface::Set_KMServerErrorCode(int)'
c:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\offbr\AppData\Local\Temp\go-link-1437089264\000011.o:C:\projects\golang\shtrihm\app\classic_fr_drv_ng_go/classic_interface_wrap.cxx:24548: undefined reference to `classic_interface::Set_KMServerCheckingStatus(int)'
c:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\offbr\AppData\Local\Temp\go-link-1437089264\000011.o:C:\projects\golang\shtrihm\app\classic_fr_drv_ng_go/classic_interface_wrap.cxx:24642: undefined reference to `classic_interface::Set_WaitForPrintingTimeout(long long)'
c:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\offbr\AppData\Local\Temp\go-link-1437089264\000011.o:C:\projects\golang\shtrihm\app\classic_fr_drv_ng_go/classic_interface_wrap.cxx:24654: undefined reference to `classic_interface::Get_WaitForPrintingTimeout() const'
c:/gcc/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\offbr\AppData\Local\Temp\go-link-1437089264\000011.o:C:\projects\golang\shtrihm\app\classic_fr_drv_ng_go/classic_interface_wrap.cxx:24878: undefined reference to `classic_interface::setLogCallback(void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
collect2.exe: error: ld returned 1 exit status```

**Comment by offbrok** [comment]
На linux собирается cmake, на винде не собирается

**Comment by offbrok** [comment]
```
C:\projects\golang\shtrihm\app>cmake --build .
Scanning dependencies of target classic_fr_drv_ng_go
[ 50%] Building CXX object CMakeFiles/classic_fr_drv_ng_go.dir/classic_interface_wrap.cxx.obj
[100%] Linking CXX shared library libclassic_fr_drv_ng_go.dll
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\classic_fr_drv_ng_go.dir/objects.a(classic_interface_wrap.cxx.obj):classic_interface_wrap.cxx:(.text+0x4f): undefined reference to `crosscall2'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\classic_fr_drv_ng_go.dir/objects.a(classic_interface_wrap.cxx.obj):classic_interface_wrap.cxx:(.rdata$.refptr._cgo_panic[.refptr._cgo_panic]+0x0): undefined reference to `_cgo_panic'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\classic_fr_drv_ng_go.dir\build.make:106: recipe for target 'libclassic_fr_drv_ng_go.dll' failed
mingw32-make.exe[2]: *** [libclassic_fr_drv_ng_go.dll] Error 1
CMakeFiles\Makefile2:94: recipe for target 'CMakeFiles/classic_fr_drv_ng_go.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/classic_fr_drv_ng_go.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
```

Ошибки из cmake при сборке на windows

**Comment by offbrok** [comment]
![image](https://user-images.githubusercontent.com/25367108/221372589-9a774d17-5ce2-433e-8c01-a409a52c6db0.png)
Еле как собрал, для работы нужны вот эти либы из mingw

**Comment by swex** [comment]
1. под windows есть две сборки с msvc 2017 и с mingw 8.1(ссылки на скачивание: https://wiki.qt.io/MinGW). 
2. чтобы всё было ок, в бинарнике должен быть один c++ рантайм. То есть GO и библиотека должны быть собраны одним компилятором.
3. чтобы не сходить с ума линковкой можно воспользоваться [json-rpc](https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_jsonrpc)

**Comment by offbrok** [comment]
SWIG не генерит код под MSVC поэтому на нем не собрать, он генерирует только под GCC.
Пробовал им собирать, ругается на синтаксис CXX.

На чем у меня получилось собрать я отписал выше. Сам GoLang просто последний релиз скачал, сам не билдил его.

Благо все работает)))

Как бы не был хорош JSON RPC, он мне не нравится.
