### ISSUE TITLE
Необходимые библиотеки для Linux

### ISSUE THREAD

**Issue by SnakePliskin777** [shtrih-m/fr_drv_ng_examples#44]
Добрый вечер! Подскажите какие библиотеки требуются для запуска приложения под Linux (Астра). Под вин все работает, в проект добавляем собранный classic_fr_drv_ng_csharp.dll и classic_fr_drv_ng.dll.

Под линь кидал собранный libclassic_fr_drv_ng_csharp.so,  6 библиотек из каталога libs и парочку libclassic_fr_drv_ng.so и libclassic_fr_drv_ng.so.1.6

Не хочет запускаться ( Уже весь мозг поломал.
Может кто подскажет, заранее спасибо.

**Comment by swex** [comment]
Думаю, что версия glibc в вашей астре более ранняя чем версия с которой собиралась библиотека. Уточните версию дистрибутива, версию gcc, версию glibc?!

**Comment by SnakePliskin777** [comment]
`GNU C Library (Debian GLIBC 2.24-11+deb9u4+ci202206011834+astra3) stable release version 2.24, by Roland McGrath et al.
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 6.3.0 20170516.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
`

**Comment by SnakePliskin777** [comment]
Удивительно, но я таки завел шарманку. Странно что dotnet автоматом не линкует вложенные нативные библы, как в винде.
Запускал $LD_LIBRARY_PATH=путь_к_нативным_библам dotnet xxl.dll

Может кому пригодится.
