### ISSUE TITLE
json-rpc и массив команд

### ISSUE THREAD

**Issue by m0x3** [shtrih-m/fr_drv_ng_examples#45]
Добрый день!
Можно ли в одном вызове передать несколько команд и/или геттеров сеттеров, например, массив команд для выполнения?

**Comment by swex** [comment]
да!
и массив и свойств можно множество назначит за внутри одного обмена по websocket.
см. [примеры](https://github.com/shtrih-m/fr_drv_ng_examples/tree/master/classic_jsonrpc) и общую [спеку jsonrpc](https://www.jsonrpc.org/specification)
