### ISSUE TITLE
Помогите что не так делаю.

### ISSUE THREAD

**Issue by mongusheb** [shtrih-m/fr_drv_ng_examples#7]
Для теста написали:

![ошибка](https://user-images.githubusercontent.com/49121083/55325681-f0f35680-54af-11e9-923b-8b87fdcb6ea0.JPG)

Visual C++

Когда подключаю 
**#pragma comment(linker, "E:\mongu_dt50kg8\source\repos\ConsoleApplication2\ConsoleApplication2\classic_fr_drv_ng.lib")**

и при попытке компиляции ошибка:
**Ошибка	LNK1276	найдена недопустимая директива "E:mongu_dt50kg8source", не начинающаяся с "/"**

Может кто может помочь с этой проблемой?

**Comment by olefard** [comment]
1. Удвоить слеши или заменить на прямые.
2. Для подключения lib по идее надо использовать #pragma comment(**lib**, "путь_к_длл/classic_fr_drv_ng.lib")

**Comment by mongusheb** [comment]
Спасибо, нашли библиотеку для C#
