### ISSUE TITLE
Передача тегов комиссионной торговли

### ISSUE THREAD

**Issue by try2bajed1** [shtrih-m/fr_drv_ng_examples#9]
Добрый день, нам нужно передать 4 тега для комиссионной торговли:
Признак агента (строка, необяз.)
Наименование поставщика (строка, необяз.)
Телефон поставщика (строка, необяз.)
ИНН поставщика (строка, необяз.)
 
Не посдкажете номера регистров и примеры, где они записываются в КЯ

**Comment by swex** [comment]
**FNSendTag**
